version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: self-sni
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "${SITE_DIR:-./sites/secure-box}:/usr/share/nginx/html"
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - self-sni
    environment:
      - DOMAIN=${DOMAIN:-secure-box.ru}
      - SITE_DIR=${SITE_DIR:-./sites/secure-box}

networks:
  self-sni:
    driver: bridge