version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: self-sni
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "${SITE_DIR:-./sites/secure-box}:/usr/share/nginx/html"
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./ssl:/etc/nginx/ssl
    networks:
      - self-sni
    environment:
      - SITE_DIR=${SITE_DIR:-./sites/secure-box}
      - DOMAIN=${DOMAIN:-secure-box.ru}
    command: >
      sh -c "envsubst '$$DOMAIN' < /etc/nginx/templates/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  self-sni:
    driver: bridge