version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: self-sni-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DOMAIN=${DOMAIN} # Передаем переменную внутрь
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./${SITE_DIR}:/srv     # Используем переменную для локальной папки
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: